### ISSUE TITLE
Adicionar Portifolio do usuário

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#100]
Criar cadastro de portfólio do usuário, aonde ele pode se quiser cadastrar seus trabalhos ja concluídos para que futuras parcerias e trabalhos vejam em seu perfil.

Cadastro deve possibilitar a inclusão de nome do projeto, descrição do projeto, e fotos do projeto.

Será um nested de projetos com nested de fotos.

**Comment by leandro** [comment]
Acredito que a prioridade dessa task deva ser baixa, tendo em vista que oferecemos a possibilidade de o usuário poder adicionar links para suas redes sociais, inclusive Github e Linked.in, que de certa forma oferecem o mesmo que essa feature está especificando.

**Comment by jcottobboni** [comment]
@leandro sim realmente, a prioridade e bem baixa. O requisito surgiu de uma demanda que uma pessoa me passou , que ela teria o interesse de criar seu portfólio em nosso site, para usa-lo também como forma de apresentação dos seus trabalhos.

Porem a prioridade e bem baixa no momento.

**Comment by jcottobboni** [comment]
fechando tarefa para reorganizar
