### ISSUE TITLE
Criar Cadastro de redes Sociais

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#102]
Criar cadastro nested de redes sociais aonde o usuário em seu perfil adiciona quantas redes sociais ele quiser.

Criar tipos de redes sociais, para informar os tipos possíveis para cadastro. No cadastro de tipo ja e inserido o logo que deve aparecer no show do usuário, o link deve ser inserido no logo, criar novo padrão de upload com icon tamanho reduzido.

**Comment by leandro** [comment]
Eu acredito que dê pra simplificar essa estrutura. Apenas o link do perfil do usuário deveria ser fornecido por ele. A logo podemos pegar por conta própria de forma automatizada, baseado no domínio. Ou podemos gerar um catálogo de todos os serviços e suas respectivas logos e jogar esses logos em `assets/images/` com tamanhos pré-estabelecidos.

**Comment by jcottobboni** [comment]
Sim da para simplificar, a segunda opção e tranquila de se fazer e os logos já ficam na aplicação.Pelo domínio daria mais talvez a segunda opção fica mais leve, não sei.

**Comment by jcottobboni** [comment]
fechando issues, para organizar posteriormente
