### ISSUE TITLE
Bug - Scaffold 

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#103]
Esta gerando o botão remover errado.

**Comment by leandro** [comment]
@jcottobboni Explique melhor onde está acontecendo o bug e como reproduzir-lo.

**Comment by jcottobboni** [comment]
@leandro eu havia verificado e corrido os botões de deletar porque estavam escritos de forma errada, por isto criei esta issue para alterar o template do scaffold. Mas agora fui averiguar e ja foi corrigido, os primeiros que foram gerados penso que estava errado depois foi arrumado pelo @mgswolf .
Esta ok , fechando a issue
