### ISSUE TITLE
Upgrade da versão do Ruby

### ISSUE THREAD

**Issue by jcserracampos** [gorails/gorails#109]
A gem `burgundy` está requisitando no mínimo a versão 2.1.0 do Ruby.

Considerando que o suporte às versões 2.0.x e 2.1.x já foram encerrados, é interessante fazer o upgrade para uma versão mais recente.

Fonte: https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

**Comment by jcottobboni** [comment]
@jcserracampos e necessário atualizar mesmo. 
So temos uma limitação hoje referente a hospedagem do website que e feita no **jelastic**, e la temos disponíveis as seguintes versões:

Versão Ruby
Ruby 1.9, 2.0, 2.1, 2.2 e 2.3

Podemos atualizar para a 2.3

**Comment by jcserracampos** [comment]
@jcottobboni Acredito que a 2.3 seja suficiente.
Eu já utilizei no jelastic sem problemas e a versão 2.3.1 teve alguns bugfixes, mas nada que quebre a aplicação.

**Comment by jcserracampos** [comment]
Acredito que possa fechar a issue.

**Comment by jcottobboni** [comment]
@jcserracampos sim resolvido
