### ISSUE TITLE
Erro em teste do RSpec

### ISSUE THREAD

**Issue by jcserracampos** [gorails/gorails#111]
O Travis CI apontou um erro em um algum teste do RSpec.

`/home/travis/.rvm/gems/ruby-2.1.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:732:in`method_missing': undefined method `setup' for RSpec::ExampleGroups::EventRegistrationsController:Class (NoMethodError)`

Relacionado com: https://github.com/rspec/rspec-core/issues/1540

**Comment by marceloperini** [comment]
Já fiz essa tarefa
