### ISSUE TITLE
Não foi possível encontrar o endereço DNS do servidor de www.gorails.com.br.

### ISSUE THREAD

**Issue by jcserracampos** [gorails/gorails#121]

**Comment by marceloperini** [comment]
O servidor está fora do ar

**Comment by jcserracampos** [comment]
Alguma previsão?
Eu possuo um crédito no Jelastic. Qualquer coisa, podemos subir lá.

**Comment by jcottobboni** [comment]
@jcserracampos vou subir amanha para um servidor vps meu, esta anteriormente na jelastic, porque tínhamos créditos la fornecidos pela locaweb, mas vou colocar no meu vps privado, o preço e relativamente menor do que o jelastic, agradeço muito a oferta dos créditos, mas acho legal ja subir para um servidor mais em conta, para manter mais tranquilo quando acabar os créditos.
Quando estiver up, vamos tentar colocar alguma plataforma de doação e ja criar a transparência para que se alguém puder e quiser ajuda a manter os gastos.

**Comment by marceloperini** [comment]
Então gente, a AWS fornece um vps de 1GB de RAM e 2vCPU de graça por um ano, eu já tenho uma conta lá e já gastei esse ano grátis. Mas caso haja alguém que nunca se registrou lá e queira doar, acho que seria mais vantajoso, o que vocês acham?

**Comment by jcserracampos** [comment]
Acho que outra solução é procurar um parceiro local.
Existem empresas de hospedagem em Goiás que poderiam nos auxiliar em troca de divulgação, não?
O GoRails nem consumiria tanta banda e recursos da hospedagem.

**Comment by jcottobboni** [comment]
@marceloperini entao essa solução funciona de começo , mas ai depois e o mesmo problema da jelastic, a gente ganhou muito credito la, mas quando acabou  teve que migrar ai enrolou pra migrar, da trabalho.

@jcserracampos acho interessante essa ideia, poderia verificar isso sim.

No momento pra não ficar offline, vou subir no meu vps e ai estudamos um modo.

**Comment by jcottobboni** [comment]
Subimos temporariamente o website da gorails para o endereço
https://gorailsbr.herokuapp.com

Entre em contato comigo pelo email : jcottobboni@gmail.com @jcserracampos , quero estabelecer comunicações mais próximas com os  interessados.
