### ISSUE TITLE
Atualizar  o ruby para o 2.4.2, e rails para ultima versão 

### ISSUE THREAD

**Issue by marceloperini** [gorails/gorails#123]
Pessoal, no README.md há uma recomendação quanto ao uso do ruby 2.0.0, já que este não está mais na lista de versões suportadas pela comunidade RUBY, acredito que seria interessante utilizarmos a versão 2.4.1, que hoje é a mais atual estável.

**Comment by juuh42dias** [comment]
Eu não sei se quebraria muita coisa a mudança para o Rails 5.1.3 também, mas seria o mais indicado. :+1:  Se alguém quiser fazer o update aí e criar um PR :smile:

**Comment by marceloperini** [comment]
estou resolvendo uma issue já testando no ruby 2.3.1, aparentemente com essa versão está ok. Mas não testei com a versão 2.4.1.

**Comment by juuh42dias** [comment]
Acho que vai ter problemas com a versão do Carrierwave. Eu não sei se seria o mais indicado remover as 'travas' das versões no Gemfile, mas permitiria ao menos atualizar as gems no projeto.

**Comment by juuh42dias** [comment]
Acredito que teve mudanças em métodos dos Oauth's nas versões novas também.

**Comment by jcserracampos** [comment]
Os testes estão cobrindo as coisas mais críticas?

**Comment by marceloperini** [comment]
Acredito que não, pelo que vi, os testes não estão cobrindo tudo

**Comment by jcottobboni** [comment]
não estão cobrindo todas as funcionalidades ainda, e necessário melhorar eles posteriormente.
seria muito bom atualizar o projeto para nova versão do rails e do ruby, porem creio que seja um trabalho considerável pois deve analisar toda a aplicação e suas funcionalidades para que nada quebre, inclusive gemas e dependências.

**Comment by jcottobboni** [comment]
Acho que esta tarefa e a mais importante, temos que atualizar o projeto, enquanto esta pequeno. Nao e bom prosseguir desenvolvendo mais coisa, com projeto desatualizado.
