### ISSUE TITLE
Grupo no telegram

### ISSUE THREAD

**Issue by jcserracampos** [gorails/gorails#125]
Eu estava vendo uma publicação da Juliana Dias no Facebook e estava pensando em como um grupo seria bom para podermos trocar ideias e fazer o projeto andar mais rápido e até mesmo podermos trocar conhecimento.
O que acham?

**Comment by juuh42dias** [comment]
Já temos um grupo no Telegram, @jcottobboni  pode postar o link do grupo?

**Comment by jcottobboni** [comment]
Verdade @jcserracampos acho muito bom termos contato em outras plataformas, temos grupos nestas duas:
Link Whatsapp: https://chat.whatsapp.com/44BjLVVGeotHxvmN3xO3na
Link telegram: https://t.me/joinchat/DDWpzAgPf9f-uLnggvZJAA

**Comment by juuh42dias** [comment]
Não esquecendo também do [Slack](go-rails.slack.com)
