### ISSUE TITLE
Melhorar Alertas

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#13]
Foi inserido no sistema alertas javascript com:
http://ersu.me/example/001-basic#example-frame

melhorar o uso do plugin para que diferencie alert, error, notice, warning com o tema basico do amaran

**Comment by fabio-araujo** [comment]
Implementado

**Comment by jcottobboni** [comment]
Todos os alertas estão vermelhos agora, implementar cores para os diferentes tipos de alertas
