### ISSUE TITLE
Erro auth no login do google

### ISSUE THREAD

**Issue by helioborges** [gorails/gorails#145]
Verificar os tokens para login e cadastro de usuário com o google, que hoje encontra-se com erro.
Verificar se mudou algo na app, ou se é apenas erro mesmo com token inválido

**Comment by jcottobboni** [comment]
resolvido, login com google funcionando, removi os outro logins sociais, enquanto não estão todos em funcionamento, a medida quer forem corrigidos, habilitem novamente

**Comment by helioborges** [comment]
Ainda está com erro


400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://gorails.com.br/users/auth/google_oauth2/callback, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/262791497357-gsesbhflmjhh1lf8btiulor0358m3v9r.apps.googleusercontent.com?project=262791497357 to update the authorized redirect URIs.

Learn more

Request Details
That’s all we know.

**Comment by jcottobboni** [comment]
realmente faltava entrada , para o dominio sem www, no auth do google, resolvido
