### ISSUE TITLE
Criar Estrutura blog

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#17]
Criar crud blog de noticias, estas serão referentes a assuntos interessantes que queremos divulgar, eventos, cursos, novidades(raisl, ruby, dev,etc).

**Comment by ocsjwolf** [comment]
Assign for me

**Comment by leandro** [comment]
@jcottobboni Acredito que tudo deveria usar a mesma estrutura de dados e mesmo models. O que diferiria um post de notícias de um post de tutorial ou artigo seria flags ou tags que passaríamos a usar. Assim evitaríamos código redundante tanto no back-end quanto no front-end.

**Comment by jcottobboni** [comment]
@leandro sim esta correto como já discutimos nas reuniões.
Esta tarefa foi criada antes e me esqueci de fecha-la.
Requisitos  serão satisfeitos pela issue #63
