### ISSUE TITLE
Campo Telefone e Celular no editar perfil, só  permite 8 dígitos

### ISSUE THREAD

**Issue by helioborges** [gorails/gorails#178]
http://www.gorails.com.br/users/edit

Fica faltando mais um dígito ao digitar o celular.

Fazer a correção, e de uma maneira em que a máscara na tela (tanto no formulário quanto no show) não estrague com o novo dígito

fique:

(62) 9XXXX-XXXX
ou
(62) 9 XXXX-XXXX

**Comment by saviocord** [comment]
tentarei fazer esta.
