### ISSUE TITLE
Arrumar os ícones no rich text editor

### ISSUE THREAD

**Issue by helioborges** [gorails/gorails#227]
Nos lugares que usamos rich text editor (form de paginas, blog, etc) os ícones de formatação de texto não estão aparecendo.

Pode ser um problema de fonte, ou então um problema de imagem.

**Comment by marceloperini** [comment]
Estou achando o layout muito "apertado" também
![screenshot_2017-10-10_13-14-41](https://user-images.githubusercontent.com/3015835/31397687-0fdbaee4-adbd-11e7-896e-64c21ddd7a74.png)

**Comment by jcottobboni** [comment]
@helioborges era um problema de font, de css, de js

**Comment by jcottobboni** [comment]
@marceloperini creio que o layout não esta todo configurado para os diferentes tamanhos de tela, vou criar uma issue para avaliar isto
