### ISSUE TITLE
Gerar Tela de Confirmação de presença

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#24]
Criar uma estrutura para confirmar a presença do inscrito no evento , tela disponível somente para administradores.

**Comment by jcottobboni** [comment]
@washingtonbezerra32 você comentou que estava fazendo esta estrutura precisaremos dela um pouco mais rápido porque já temos uma lista de presentes no evento que deve ser lançada.
Esta funcionalidade também pode ser divida se for o caso para atender a urgência pode se criar um importador que pegue o xls com cpf do usuário e id de evento e confirme a presença do mesmo. E outra tarefa para fazer a tela de confirmação que será mais complexa.

@leandro @henriquegeek @helioborges @ocsjwolf O que acham ?

**Comment by leandro** [comment]
@jcottobboni Qual é o workflow atual que se tem no codebase? Não existe nenhum tipo de confirmação? Qual é o intuito de um administrador poder confirmar (com poderes de aceitar ou negar?) a presença de alguém que já demonstrou interesse em se cadastrar em um evento ao preencher o formulário?

**Comment by jcottobboni** [comment]
@leandro hoje não existe confirmação no workflow, o evento e criado, os usuário podem se inscrever no evento bem simples. 

A confirmação de presença aqui ficou mal explicada. Esta confirmação de presença quando foi pensada seria uma tela aonde as pessoas que ficariam no credenciamento do evento pudessem pesquisar e confirmar que aquela pessoa esteve presente no evento já em nosso portal. Então apos o evento a listagem que aparece no show do evento de inscrições confirmadas seria trocada pela listagem de pessoas que compareceram no evento e também no perfil da pessoa apareceria que ela esteve no evento "X". 
Como está função não estava desenvolvida hoje temos um documento xls com a lista de usuário e os que se credenciaram no dia do evento estão destacados. Precisamos importar esta lista. 
Creio ser importante também ter a função de importação porque futuramente ainda pode ocorrer algum dia ser usada, um exemplo quando no evento por eventualidade não ter conexão com a internet no dia e ser necessário usar um documento xls novamente para credenciamento, já que no momento não seria possível acessar o portal.
A estrutura de banco de dados não esta pronta para receber nenhuma destas funções.


Agora creio que oque você pensou @leandro não existirá. Um usuário poderá ser receber sua inscrição negada em um evento creio que somente por falta de pagamento mediante a eventos pagos. Mais isto virá em outra issue futuramente.

Outra função que pode derivar desta e a criação de um cron para disparar automaticamente emails de confirmação que o usuário irá mesmo ao evento , isto alguns dias antes do mesmo acontecer, quando o usuário clicar em um link no e-mail confirmará sua ida ao mesmo. Isto servirá para relembrar os usuários do evento e para que possamos antes do mesmo mensurar a quantidade de presentes.

**Comment by leandro** [comment]
@jcottobboni Ahhh sim! Agora tudo ficou mais claro. Valeu pela explicação. Se o @washingtonbezerra32 não puder trabalhar nessa issue, eu posso me candidatar. 👊

**Comment by jcottobboni** [comment]
@leandro Vamos aguardar a resposta do @washingtonbezerra32 se eles estiver ocupado agora faz pra gente está Leandro que a prioridade dela está um pouco alta

**Comment by leandro** [comment]
@jcottobboni Beleza. Acho que entendi o que você disse. Algumas palavras ficaram meio desconexas no seu comentário acima.

**Comment by jcottobboni** [comment]
@leandro comentei no celular aqui rápido. Creio que talvez o whashington esteja ocupado neste momento, se for o caso você assume a issue. Estamos precisando desta funcionalidade agora.

**Comment by jcottobboni** [comment]
@leandro pode assumir a issue já falei com @washingtonbezerra32

**Comment by leandro** [comment]
@jcottobboni De novo essa issue está sem dono...é bug?

**Comment by leandro** [comment]
@jcottobboni Hahaha de novo. To achando que o Github automaticamente me tira da Issue porque não faço parte do projeto.
