### ISSUE TITLE
Ao editar notícia o usuário do post está alterando

### ISSUE THREAD

**Issue by helioborges** [gorails/gorails#246]
Quando um usuário posta uma notícia (blog) e outro depois edita ela, o sistema está pegando automaticamente o user_id de quem editou e está substituindo com o do autor

### Steps to reproduce

Fazer um blog post com um usuário, e editar com outro usuário

### Expected behavior
O usuário que criou o post deve ser mantido como autor do post

### Actual behavior
O autor do post está modificando para quem editou pela última vez

**Comment by jcottobboni** [comment]
creio que e so remover do form o user id, e setar isto no new, ou em uma callback before_create

**Comment by RicardoVentrilho** [comment]
Já elvis...
