### ISSUE TITLE
Mudar o teaser de notícias na página inicial e no menu blog

### ISSUE THREAD

**Issue by helioborges** [gorails/gorails#252]
Hoje, se você abrir o index do gorails.com.br ele vai mostrar as notícias (blog posts) que estão com a tag notícias

mas no site mostra apenas uma pequena parte do teaser, acho que está 30 caracteres

mudar para o seguinte:

1. se houver o teaser na notícia. MOSTRAR O TEASER COMPLETO - em html
e manter o botão continue lendo

2. se não houver o teaser. MOSTRAR O TEXTO DA NOTÍCIA COMPLETO - em html

tanto no index do site, quanto no recurso de blog http://gorails.com.br/blog/posts/list

**Comment by caiofilipemr** [comment]
Fazendo
