### ISSUE TITLE
Corrigir informações na view da notícia (blog)

### ISSUE THREAD

**Issue by helioborges** [gorails/gorails#253]
Se você entrar numa notícia:

http://gorails.com.br/blog/posts/show_list?id=3

vai mostrar a baixo do título 3 informações: 

Autor, data que foi postado, quantidade que foi visualizado e quanto tempo demora para ler o post (wordcount)

- Modificar para ficar:

Autor, Data e hora que foi postado (em formato de data brasileiro)

o word count, pode retirar por completo, porque está confuso essa informação.

já a quantidade de vezes que foi visualizado, pode deixar lá, mas que essa informação apareça EXCLUSIVAMENTE para quem tem permissão de admin.

**Comment by caiofilipemr** [comment]
Tentarei está
