### ISSUE TITLE
Login não permanece após fechar o navegador

### ISSUE THREAD

**Issue by marceloperini** [gorails/gorails#254]
### Steps to reproduce

1. Abre o navegador;
2. Efetua login;
3. Fecha o navegador;
4. Abre o navegador novamente e acessa o site;

### Expected behavior
A aplicação deve manter a sessão de login do usuário, mesmo se ele fechar o navegador.

### Actual behavior
A aplicação não está mantendo o login do usuário ativo, quando este fecha o navegador.

### System configuration
**OS**: Xubuntu
**OS Version**: 16.04 LTS 
**Browser**:  [Google Chrome, Mozilla Firefox]
**Browser Version**: [62.0.3202.62 (Official Build) (64-bit), 56.0 (64-bit)]

**Comment by juuh42dias** [comment]
Está mantendo a sessão com cookies?

**Comment by juuh42dias** [comment]
@jcottobboni  já pode fechar essa...
