### ISSUE TITLE
Gerar Código de Certificado de eventos

### ISSUE THREAD

**Issue by helioborges** [gorails/gorails#255]
Criar no módulo de Registration um método que gere um código hash de não mais que 8 caracteres (pode ser letra e numeros) para ser verificado em um html de forma para autenticar um certificado emitido pela GoRails

deve usar em consideração na geração do código:

evento id + usuario id + registration id 

passando por algum algoritmo para hashear isso em uma string aleatória - de forma que você não consiga chutar a formação dele

Esse código será impresso no certificado e vai poder ser usado para validar o certificado emitido

**Comment by benhur10cp** [comment]
Estou fazendo,
