### ISSUE TITLE
Criar página para validar certificado

### ISSUE THREAD

**Issue by helioborges** [gorails/gorails#256]
Fazer depois da tarefa #255  

Criar uma pagina html com um formulário contendo apenas um campo texto para digitar um código e um botão validar. 

Ao acessar o endereço www.gorails.com.br/certificado (criar essa rota) a pessoa vai digitar o código e clicar em validar, o sistema irá passar o código pelo decodificador e irá retornar uma tela:

a) Se o código for válido, informando: 
Qual evento foi (nome com link pra página) 
quando aconteceu, 
quantas horas valem o evento (pegar do horário início e fim do evento)
o nome da pessoa
o cpf da pessoa
se ela compareceu ou não (olhando o campo presence de registration)

b) Se o código não for válido:
Mensagem de erro mostrando que o código não é valido. 
Por favor digite um código valido de um diploma emitido pela GoRails

**Comment by benhur10cp** [comment]
Estou fazendo.
