### ISSUE TITLE
Criar método que envie lembrete sobre evento

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#28]
Criar método que envie e-mail para os inscritos um dia antes do evento lembrando sobre a data e dados do evento.

**Comment by jcottobboni** [comment]
para fazer isto e necessário criar um componente que envie emails.
Pode ser feito  com e-mail no Action Mailer criando um template, ou podemos usar uma ferramenta como o mandril, ja que temos a integração com mailchimp feita, o mandril e para isto mesmo mandar e-mails de boas vindas, de lembretes, os templates podem ser feitos no mailchimp, e exportados para o mandril. 

@helioborges @leandro @henriquegeek @ocsjwolf @mgswolf 
opinen....

**Comment by leandro** [comment]
@jcottobboni Esses e-mails seriam enviados automaticamente via um cron job ou seria enviado manualmente através de acesso admin? Se for via cron job, temos atualmente privilégios o suficiente no servidor para tal execução?

**Comment by jcottobboni** [comment]
@leandro sim leandro, poderíamos implementar isto no servidor. Tenho que averiguar certinho. mas podemos colocar tarefas no cron sim se não me engano.
Mas também poderíamos usar algo como
https://github.com/javan/whenever
não?

**Comment by leandro** [comment]
@jcottobboni Pode ser. Eu nunca o usei, mas já havia ouvido falar a respeito.
