### ISSUE TITLE
Colocar no footer o icone do discord

### ISSUE THREAD

**Issue by helioborges** [gorails/gorails#315]
Não existe ainda no font-awesome, mas quando existir no font-awesome 5, atualizar o projeto e trocar o icone para o icone do discord

**Comment by yeltsinseal** [comment]
Esse ícone que está no rodapé, parece um cogumelo 😄

**Comment by helioborges** [comment]
Não tem outro cara :laughing:  é o mais próximo que eu achei no font-awesome 4.7
dizem que no 5.0 vai sair o icone do discord mas ainda não tem
até lá é esse

**Comment by lazaroalvarenga** [comment]
Já está disponível no [fontawesome](https://fontawesome.com/icons/discord?style=brands)

Alguém já está fazendo? Posso ajudar? 🙂

**Comment by marceloperini** [comment]
pode sim @lazaroalvarenga
