### ISSUE TITLE
Criar Cadastro de interesse em brindes 

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#32]
Depende da issue #31 

Criar cadastro de interesse em brindes do evento, para participar do sorteio. Mostrar alerta ao usuário apos ele se inscrever no evento. 

Deve apresentar uma tela aonde o usuário escolhe os itens que deseja concorrer no evento dentre os cadastrados para o mesmo.

**Comment by leandro** [comment]
A pergunta que fica nessa issue é: será que realmente as pessoas que atenderão ao evento marcarão devidamente os brindes que querem ganhar? Eu acho que na prática isso acaba não acontecendo.

**Comment by jcottobboni** [comment]
Essa issue surgiu de uma questão no evento passado tínhamos vários brindes e alguns mais específicos como por exemplo os cursos para java e linux, talvez certas pessoas não teriam interesse. então pensamos em colocar um checklist para escolha filtrando mais assim os interessados para que os brindes específicos não fossem "desperdiçados", se a caso o ganhador não tivesse interesse em usa-lo. Mas por falta de tempo não implementamos esta issue, e também concordo que ela e pouco aplicável.

**Comment by jcottobboni** [comment]
Se ninguém achar que ela deve permanecer, podemos fechar.
Aguardo opiniões.

**Comment by leandro** [comment]
Então façamos o seguinte a respeito dessa issue: deixemos ela maturar por
aqui. Se houver novamente a real necessidade de ela existir, nós avaliamos
no momento certo os requerimentos (que estarão fresquinhos em nossas
mentes) e assim podemos também definir melhor como faríamos para que todos
os usuários envolvidos possam usar esse recurso de forma certeira.
