### ISSUE TITLE
Erro nos testes

### ISSUE THREAD

**Issue by marceloperini** [gorails/gorails#326]
### Steps to reproduce

* bundle exec rspec

### Expected behavior

* Deveria rodar os testes

### Actual behavior

![screenshot_2017-11-01_10-07-01](https://user-images.githubusercontent.com/3015835/32274143-a871141a-beec-11e7-9bc6-bf7d1bbf819d.png)

### System configuration

**OS**: Arch Linux

**OS Version**: 2017.11.01

**Browser**: --

**Browser Version**: --

**Comment by juuh42dias** [comment]
@marceloperini vou dar uma checada por aqui.

**Comment by juuh42dias** [comment]
@marceloperini  @jcottobboni  esta gem foi removida? Tem outra em mente ou vai desenvolver algo assim na mão?

**Comment by marceloperini** [comment]
Acredito que o problema esteja no migrate de criação da tabela gamification_item_groups

**Comment by jcottobboni** [comment]
este problema ocorre quando se cria um user e ele adiciona o inventario padrão a ele, mas para isso precisa ter alguns dados na tabela, antes de rodar os testes e necessário rodar o rake dev:setup para popular os dados padrões.

**Comment by marceloperini** [comment]
é rake db:setup. Acabei de reproduzir aqui, vou subir a correção

**Comment by marceloperini** [comment]
@jcottobboni onde fica esse model Gamification::ItemGroup?

**Comment by jcottobboni** [comment]
@marceloperini  fica dentro da engine go_gamification, app/models/gamification/item_group.rb
Esta sobre o namespace Gamification

**Comment by jcottobboni** [comment]
`module Gamification
  class ItemGroup < ApplicationRecord
    has_many :items,class_name: 'Gamification::Item',foreign_key: :gamification_item_group_id
  end
end`

**Comment by marceloperini** [comment]
Cara não tem nenhum model chamado ItemGroup dentro desse module

![screenshot_2017-11-05_15-21-44](https://user-images.githubusercontent.com/3015835/32417218-309f9142-c23d-11e7-8049-a824b0e5173f.png)

**Comment by jcottobboni** [comment]
@marceloperini realmente nao tinha, tava faltando pull request do meu repo pro master da gorails, da um pull request ai agora, que vai ir
