### ISSUE TITLE
Mesmo logado eu consigo acessar /users/sign_up

### ISSUE THREAD

**Issue by lazaroalvarenga** [gorails/gorails#385]
O ideal seria redirecionar para a página inicial do usuário ou informar ali que já estou logado.

**Comment by plcosta** [comment]
Também não consegui reproduzir essa issue. Aqui apresentou o alert que já estava logado.

![screenshot 2018-10-31 22 43 15](https://user-images.githubusercontent.com/1139813/47827756-6f5f9700-dd5e-11e8-8c61-23e5e8ce1760.png)
