### ISSUE TITLE
Criar página Quem Somos

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#47]
a pagina ja existe em paginas/quem-somos...definir layout e conteúdo .

**Comment by jcottobboni** [comment]
@helio esta e uma boa para você fazer pra gente

**Comment by jcserracampos** [comment]
Vamos tentar não fazer aniversário de dois anos das issues.

**Comment by jcottobboni** [comment]
Verdade ....essa aqui tá urgente

**Comment by jcottobboni** [comment]
fechando, esta tarefa sera feita na issue #64
