### ISSUE TITLE
Criar Estrutura para upload de documentos

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#5]
Criar estrutura para usar com paperclip/carrierwave  para upload de documentos(images, pdfs, etc).

Deve ser possível fazer upload para qualquer classe do sistema

Criar o componente com as partials para ser possível adicionar múltiplos documentos e visualizar os documentos adicionados.

**Comment by ocsjwolf** [comment]
Pretende usar um origin:references pro origem_id ou um origin_id:integer mesmo?

**Comment by jcottobboni** [comment]
Usando a CarrierWave do jeito que você falou nem precisa destes campos. atualizei a tarefa.
