### ISSUE TITLE
Colocar cpf como unico

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#53]

**Comment by jcottobboni** [comment]
Exemplo
validate :cpf_unico

def cpf_unico
    if self.cpf and !self.cpf.to_s.empty? and Usuario.where(cpf: self.cpf).where('id <> ?', self.id || 0).first
      errors.add(:cpf, "já está sendo usado")
    end
end

**Comment by fabio-araujo** [comment]
Implementado.

Não sei porque essa gem brcpfcnpj não estava aceitando utilizar o validate_uniqueness_of ele cria uma classe em tempo de execução e seta o cpf como numeric e buga o validates, não quis perder tempo com isso e fiz um custo validate.
