### ISSUE TITLE
Criar Patrocinadores/Apoiadores

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#6]
Depende da tarefa #5
Criar CRUD para apoiadores, eles podem ser de três tipos(patrocinadores, realização, apoiadores)
o cadastro deve conter o basico:
name caracter varying (255)
link caracter varying (255)
order integer 
event_id
site boolean
nested documentos poder adicionar a imagem do patrocinador atentar-se ao tamanho das imagens geradas.

Um patrocinador, realizador e apoiador pode ser geral do site ou de um evento especifico. Eventos terão listagem de patrocinadores e apoiadores e o site terá no footer uma listagem dos apoiadores .

**Comment by ocsjwolf** [comment]
#5 seguindo a task 5 vou ficar com esta tbm.

**Comment by jcottobboni** [comment]
@ocsjwolf  ok, atribuido
