### ISSUE TITLE
Criar Tutoriais

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#63]
Este funcionalidade será para que qualquer usuário do site possa postar/ler/avaliar/propor mudanças/ de tutoriais. 

Um tutorial será um texto postado que explica como fazer certa "coisa", verificar no layout usado one ui tem uma área  que define layouts de código que esta área possuirá.

Cadastros necessários para efetuar esta tarefa, tags, categorias, temas.

Tags => ["rails","ruby","Web"]
Categoria => ["Noticias", "Tutoriais","ScreenCasts"]
Temas => ["Gorails","Atualizações","Rails","Ruby","Intalação",]

Categories
 has_many :themes 

Themes
 belongs_to :category

Deve haver um novo perfil moderator, este perfil  será responsável por avaliar todos os tutoriais postados por pessoas, quando uma pessoa que não e um moderator posta um usuário o campo published deve vir false, somente o moderator ou admin poderão publicar este tutorial, podendo edita-lo antes da publicação.

Este componente deve ser desenvolvido em dois lugares backend e frontend, views diferentes para diferentes usuários e pessoas logadas ou não.

Um tutorial deve conter uma área lateral que sejam os links para os tópicos dentro do mesmo.
Deve ser possível criar um tutorial a partir de outro tutorial, copiar o mesmo e editar as informações, isto servira por exemplo um tutorial de configuração do ambiente rails no mac, pode conter uma variação de como configurar no unbuntu, estas versões devem ser linkadas, para que seja fácil o usuário encontra-las.
um tutorial deve ter tabs ou outra estrutura que mostre as variações do mesmo

Esta função deve ter no show um interpretador de markup language , uma boa gema a ser utilizada e a redcarpet. e no edit pode se usar o bootstrap editor markdown para facilitar a formatação do texto. E necessário o markdown pois os tutoriais conterão área de códigos.

Um post deve pertencer a um tema, deve conter os campos titulo, texto, autor, publicado, deve conter comentários.

Deve ser possível inserir tags nos posts

**Comment by jcottobboni** [comment]
@helioborges @henriquegeek @leandro @ocsjwolf @jonatasrancan @mgswolf 
Ajudem a construir oque deve ser esta função uma das mais importantes do sistema.

**Comment by jonatasrancan** [comment]
@jcottobboni quando vc fala ali em cima `cadastros necessários`, são cruds neh?

**Comment by jcottobboni** [comment]
@jonatasrancan sim são os cruds que esta tarefa precisará , ainda não criei tarefas separadas para ele pois queria discutir primeiro esta tarefa.

**Comment by henriquegeek** [comment]
@jcottobboni Esta funcionalidade no caso se trata de um Blog? Se for isso, sou a favor de integrar alguma ferramenta no lugar de desenvolver, veja o exemplo da He:labs https://journal.helabs.com e a Codeminer 42 https://medium.com/codeminer-42/trending, 2 das maiores empresas de desenvolvimento em Rails, eles não tiveram pudor em usar o medium no lugar de construir sua própria solução no caso um blog para compartilhar e difundir sua cultura e ideias, não me leve a mal, gosto muito de desafios e de programar, mas neste caso especifico acredito que se criássemos um centralizador de publicações no medium apontando para http://tutoriais.gorails.com.br já poderíamos ir criando material para a comunidade produzindo valor de forma imediata.

**Comment by jcottobboni** [comment]
@henriquegeek sim esta funcionalidade servirá para alimentar todo conteúdo de texto do gorails, blog, tutoriais, e demais textos como noticias. Já havia olhado o meddium e estou pensando o seguinte.
Motivos da helabs ter migrado:
Queremos ser lidos => O médium tem uma gama maior de pessoas lendo diariamente, então penso que atingir um maior publico la do que no website da gorails seria realmente mais fácil, porem também não e tao fácil assim deve-se construir um publico oque não e da noite para o dia.

Propriedade intelectual => O problema citado pela helabs e porque as pessoas que escreviam no blog eram funcionários da empresa e logo quando saiam do grade de pessoas, ficavam de fora da ferramenta e perdiam o conteúdo. Na gorails isto não iria acontecer pois somos uma iniciativa feita pela comunidade para a comunidade aonde todos tem acesso e sempre terão.

Queremos estar perto da comunidade=> pelo que entendi eles quiseram dizer que ao utilizar uma ferramenta que outras grandes empresas usam estão mais perto da comunidade que e nosso intuito também. 

Pontos a se discutir para a gorails
Ja conversei um pouco sobre isso com @leandro, com base em nossos objetivos de gameficação queremos recompensar a pessoa que publica posts, tutoriais, e noticias em nosso portal. Por isto precisamos de um controle próximo para que a aplicação saiba quantos de cada artigo foram postados, atualizados e etc. Bem como comentários nos posts, e avaliações positivas no conteúdo, outra coisa que também acho importante e uma função que possibilite escrever artigos similares para os posts e que isto fique agregado de uma certa maneira.

Isto serviria por exemplo quando uma pessoa escreveu um tutorial de como instalar o rails no unbuntu 12.04, e outra pessoa cria um novo tutorial a partir daquele para o unbuntu 15. Os dois ficam ligados para serem encontrados de uma maneira fácil. No entanto esta e uma funcionalidade que acho legal.
Agora a parte de ter controle dos posts e tutoriais, e bem complicado porque não poderíamos construir a parte de gamificação que creio ser uma parte bem legal que irá agregar ao futuro da gorails.

Pelo que li rápido o meddium não tem uma api  completa que possibilite buscar a quantidade de posts por usuário, ou comentarios e likes no mesmo. O que seria muito bom pois então poderíamos ate cogitar. Me corrija @henriquegeek  se estiver errado, não conheço a ferramenta e fiz só uma busca rápida aqui.

Avaliem os pontos que comentei ali em cima, e vamos ver. Estou querendo chegar a uma solução boa, sou super adepto de usar boas ferramentas prontas, e acho que nao devemos mesmo ficar tentando reinventar a roda, porem temos algumas necessidades especificas aqui que devem ser supridas.

**Comment by henriquegeek** [comment]
Legal @jcottobboni, quanto a api não cheguei a pesquisar a única coisa que testei foi o processo de custom domain, mas vou pesquisar, acho que poderíamos fazer um hangout para decidir a respeito disso e depois levantar uma votação não sei.

**Comment by jcottobboni** [comment]
fechando tarefa, irei abrir outras, com conteudo mais definido
