### ISSUE TITLE
Inserir informações do projeto no site

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#64]
O website deve conter uma área que defina que ele e um projeto open source, e esta área deve conter as informações para que qualquer usuário que acesse e queira começar a contribuir com o projeto saiba como fazer isso.

**Comment by jcserracampos** [comment]
Não podemos juntar esta issue com a #47 e apontar para a página no github? Aqui sempre teremos informações atualizadas sobre como contribuir.

**Comment by juuh42dias** [comment]
Eu voto na ideia do @jcserracampos

**Comment by jcottobboni** [comment]
achei legal, acho que podemos sim fazer isto

**Comment by jcottobboni** [comment]
coloquei o link do quem somos, para a pagina do github
