### ISSUE TITLE
Brakeman Report - File Access

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#86]
In app/controllers/paginas_controller.rb

![capturar](https://cloud.githubusercontent.com/assets/3996742/14971032/b1034050-10a4-11e6-87f0-9fbbfff2b148.PNG)

**Comment by leandro** [comment]
O ideal seria, pelo menos por agora, criar um arquivo .yml com uma whitelist das páginas existentes que podem ser carregadas. Criar um `config/settings.yml` para isso seria uma boa. Mas essa foi a primeira idéia que me veio à cabeça. Talvez existam melhores.

Devo comentar aqui em inglês? Estou na dúvida.

**Comment by jcottobboni** [comment]
Sim este e um método , neste link tem outros.
[](http://gavinmiller.io/2015/fixing-file-access-vulnerabilities-in-ruby-and-rails/)

Não acho que vamos manter somente o código e commits em inglês mesmo, aqui pode ser português.

**Comment by jcottobboni** [comment]
teste
