### ISSUE TITLE
Criar Transparência no Portal

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#89]
**Como usuário logado no website da GoRails **
**Eu quero** visualizar as despesas e receitas por data 
**Para que** eu possa acompanhar os gastos da associação

**Critério de Aceitação**
- O sistema deverá permitir que o usuário devidamente logado possa visualizar a transparência de despesas da organização
- O cadastro de despesa e receita deve apresentar os campos mínimos: Objeto, Pessoa, valor, status, data da despesa/receita, data de consolidação despesa/receita, multiplos anexos, observação.
- A inserção, edição, remoção de dados deve ser feita somente para os administradores
- O sistema deverá permitir exportar o extrato para um relatório csv e xls
- Os botoes das ações de inserção, edição, remoção somente deverão aparecer para os administradores.

Exemplo da planilha e telas possíveis para a função a ser desenvolvida.

![novadespesa](https://cloud.githubusercontent.com/assets/3996742/15054446/f203a262-12dd-11e6-8c9b-a7f5587368a8.PNG)
![novareceita](https://cloud.githubusercontent.com/assets/3996742/15054447/f313f2b0-12dd-11e6-8f12-6c425acb830b.PNG)
![exemplo](https://cloud.githubusercontent.com/assets/3996742/15054452/f6dbcd50-12dd-11e6-9402-9767b7979a67.PNG)
![index](https://cloud.githubusercontent.com/assets/3996742/15054455/fb08cb4e-12dd-11e6-86e2-b46b353dd6b7.PNG)
![index detalhado](https://cloud.githubusercontent.com/assets/3996742/15054457/fd803c72-12dd-11e6-960d-a08773657f5f.PNG)

**Comment by leandro** [comment]
Sugiro que o formato de exportação seja mais simples e aberto, como um mero CSV.

**Comment by jcottobboni** [comment]
Concordo @leandro o formato deve ser csv.

**Comment by henriquegeek** [comment]
CSV e XLS também.

**Comment by jcottobboni** [comment]
@henriquegeek Pode ser e bem fácil o csv e xls

**Comment by ocsjwolf** [comment]
@jcottobboni Contadores curtiram a ideia do xls hehe

**Comment by henriquegeek** [comment]
Seria legal ter um link para para baixar os comprovantes de pagamento, em uma repositório como o S3.

**Comment by jcottobboni** [comment]
@henriquegeek Sim com certeza seria interessante isto, vou adaptar a tarefa, coloquei na imagem sobre o anexo mas esqueci de detalhar. E muito importante isto.

**Comment by jcottobboni** [comment]
@henriquegeek @helioborges @ocsjwolf @leandro 
Deve ter a função repetir com a periodicidade da receita, para o caso de receitas ou despesas fixas?
oque vocês acham.

**Comment by ocsjwolf** [comment]
@jcottobboni Tem que ver o modelo de como vamos fazer né

**Comment by henriquegeek** [comment]
João como será feito o portal da transparência?
Acho que poderia ser uma API em ROR(separado do portal do GoRails), com uma interface admin feita em angular, sendo consumida pelo portal do GoRails.

**Comment by leandro** [comment]
Acho que a idéia dos comprovantes é importante, porém subir as imagens dos comprovantes para o S3 pode ser implementado separadamente numa issue nova de forma incremental após essa issue ter sido implementada.

**Comment by jcottobboni** [comment]
@leandro sim, ate porque na aplicação já tem implementado o anexo múltiplo , então faz normal depois vê a possibilidade de refazer o modulo de upload de doc e imagens para S3 ou outro parecido.

**Comment by jcottobboni** [comment]
@henriquegeek Não sei, oque todos acham, eu tinha pensado em fazer junto ao projeto principal mesmo, achei legal sua ideia, mas quais os pontos que você esta preocupado para ter que fazer separado?

**Comment by leandro** [comment]
Acredito que a idéia deva ser implementar de forma simples e incremental qualquer feature que seja, inclusive essa da qual estamos falando. Logo, entendo que a sugestão do @henriquegeek possa ir na contramão dessa intenção. Vejo essa sugestão como uma otimização precoce. Pelo menos não consegui enxergar benefícios nessa arquitetura sugerida, tendo em vista os custos de implementação.

**Comment by henriquegeek** [comment]
A ideia de se fazer separa é porque teríamos as coisas modularizadas e separadas em serviços, isso ajuda muito depois quando for dar manutenção ou implementar novas issues. Acredito que se fizermos tudo em uma arquitetura monolítica depois teremos uma dor de cabeça com um elefante branco nas mãos.

**Comment by leandro** [comment]
Eu entendo sua preocupação, mas se a sua idéia não for devidamente planejada e executada, ela mais irá atrapalhar do que ajudar.

Para ilustrar o que eu estou falando:

![Monolith vs. Microservices]
(http://image.slidesharecdn.com/statelessauthenticationformicroservices-141211091054-conversion-gate02/95/stateless-authentication-for-microservices-12-638.jpg?cb=1418289749)

Partir para o rumo de micro-services envolve adoção de uma série de outras tecnologias que no momento não estamos precisando lidar. E partir para esse rumo pode dificultar um pouco a atratividade para que outras pessoas possam contribuir com o projeto com uma certa facilidade.

A questão é que se partíssemos para esse rumo agora, teríamos bastante trabalho extra para "services provisioning & orchestration" sem retorno inicial nenhum e isso envolveria Docker no ambiente de desenvolvimento, chef/ansible/puppet em produção e etc. Seria necessário muita configuração inicial.

IMO, preocuparmos com isso num estágio tão inicial seria fugir do foco de desenvolver "produtos" dentro dos objetivos pretendidos para a comunidade e seria uma espécie de "caçar sarna para coçar".

De qualquer maneira, sou favor da democracia e sendo assim, se julgarmos necessário, podemos optar por uma votação dentro desse contexto.

**Comment by helioborges** [comment]
Galera, acho que vocês estão viajando. 

É só um local para colocarmos as informações. Não é um serviço de contabilidade, nem um portal da transparência. é uma função Muito pequena, muito restrita, que não vai ter novos requisitos...

a solução mais simples é um cadastro simples no nosso portal, na aplicação mesmo e pronto.

**Comment by leandro** [comment]
Pois então, concordo plenamente. Mesmo que possa *haver a possibilidade de no futuro* necessitar-se de ter algo mais profissional e organizado dentro do contexto da contabilidade, isso poderia ser melhorado com o tempo.

**Comment by jcottobboni** [comment]
@leandro Concordo.. Creio que a função hoje é muito simples.. A ideia do Henrique e boa e valida com certeza.. Se houver alguma função deste nível mais a frente vamos considerar as possibilidades. Mas esta não vejo necessidade.

**Comment by henriquegeek** [comment]
Realmente pessoal analisando pelos comentários de vcs, realmente trata-se apenas de uma feature e não uma implementação de um serviço.

**Comment by jcottobboni** [comment]
fechando pra organizar
