### ISSUE TITLE
Criar cadastro de contratos

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#96]
Criar cadastro de contatos, telefones, emails nested no perfil do usuário.
Mostrar no show do usuário depois de cadastrado.
Creio não ser necessário a criação de tipos já que são poucos e fixos.

contatc:string 
contatc_type:string => select 
user_id:references

**Comment by henriquegeek** [comment]
No caso não seria melhor separar redes sociais de contatos?

**Comment by leandro** [comment]
Concordo um pouco com o Henrique. Não acho que redes sociais de forma geral sejam "tipos de contato". De forma geral, os vejo como meros links, que podem ser exibidos de formas diferentes, dependendo do domínio de cada link, com exceção dos verdadeiros contatos: telefones e e-mails.

**Comment by jcottobboni** [comment]
@henriquegeek @leandro sim creio que podemos separar, retirei a ideia inicial, de uma aplicação que conheço pelo jeito que foi feito unificado para não criar duas estruturas que são super simples separadas, mas escrevi assim somente para ter ideia. O ideal e criar separado mesmo penso, pois são coisas diferentes. O trabalho vai ser pouco a mais. vou desmembrar a tarefa.

**Comment by jcottobboni** [comment]
Atualizei esta issue, e mudei as redes sociais para outra

**Comment by jcottobboni** [comment]
fechando tarefa para reorganizar
