### ISSUE TITLE
Adicionar campo na view do usuário

### ISSUE THREAD

**Issue by jcottobboni** [gorails/gorails#99]
Adicionar campo visto por ultimo na view do usuário, não me recordo se isto já vem com a devise, se não implementar.

**Comment by jcserracampos** [comment]
@jcottobboni O campo é para ser exibido na rota `users#show`?
Tem alguma de onde deve ficar?

**Comment by jcottobboni** [comment]
@jcserracampos sim e para ser exibido nesta rota.
quando ao posicionamento do campo pode criar um novo quadro  a direita para colocar algumas informações generalizadas.
a tela e dividida no quadro da capa, abaixo um quadro a esquerda para implementar uma futura timeline. e quadros a direita com informações divididas.
Você pode criar mais um para inserir esta informações ou suprimir os outros e colocar todos em um quadro único a esquerda. 

O layout precisa de algumas melhoras em certos lugares então sintam-se livres para dar dicas e melhorar algumas partes por favor.
